Session support implementation
ummarbhutta/iotweb pull request #1
Opened 2017-03-15 11:05 UTC by mshoaibijaz

2017-03-15 11:22 UTC, ummarbhutta requested changes
Please make these fixes, against my first feedback

2017-03-15 11:22 UTC, ummarbhutta commented on IotWeb NET45/Helper/SessionFileStorageHandler.cs
> +        {
Please implement it, Even if you are not using it, put a valid implementation here

2017-03-15 11:22 UTC, ummarbhutta commented on IotWeb NET45/IotWeb NET45.csproj
> +    </Reference>
What is this for?

2017-03-15 11:22 UTC, ummarbhutta commented on IotWeb Portable/Http/HttpRequestProcessor.cs
> +                    }
Remove the above if/else block if it is not required.

2017-03-15 11:22 UTC, ummarbhutta commented on IotWeb Portable/Http/HttpRequestProcessor.cs
> +                    }
Remove it as well if not required, or put a valid logic inside if/else block.

2017-03-15 11:22 UTC, ummarbhutta commented on IotWeb Portable/Http/SessionDictionary.cs
> +    public class SessionDictionary : IDictionary<string, string>
Remove this class if it is not required, you can use use simple dictionary

2017-03-15 11:22 UTC, ummarbhutta commented on IotWeb UWP/Helper/SessionFileStorageHandler.cs
> +            throw new NotImplementedException();
Implement this method

2017-03-16 11:03 UTC, mshoaibijaz commented on IotWeb NET45/Helper/SessionFileStorageHandler.cs
> +        {
Implemented

2017-03-16 11:04 UTC, mshoaibijaz commented on IotWeb Portable/Http/HttpRequestProcessor.cs
> +                    }
Code refactored.

2017-03-16 11:04 UTC, mshoaibijaz commented on IotWeb Portable/Http/HttpRequestProcessor.cs
> +                    }
Code refactored.

2017-03-16 11:04 UTC, mshoaibijaz commented on IotWeb Portable/Http/SessionDictionary.cs
> +    public class SessionDictionary : IDictionary<string, string>
Class has removed.

2017-03-16 11:05 UTC, mshoaibijaz commented on IotWeb UWP/Helper/SessionFileStorageHandler.cs
> +            throw new NotImplementedException();
Implemented.

2017-05-17 07:08 UTC, ummarbhutta requested changes
One possible issue
- There is a concept of Filters in this server, and we can use request, response and HttpContext in it, and manipulate them as well. I assume from looking into code that if someone has used after filters and have made some possible changes in session then it will not be written to session file. Please have a look in it.
- Secondly can we make session access in HttpHandler more easier than this? like ASP.NET controller? where session is available through out the controller class, and we don't have to pass it to all child function (consider of a complicated HttpRequestHandler, where we need to call many child functions to process a request and session is required in all of them)

2017-05-17 07:08 UTC, ummarbhutta commented on IotWeb Portable/Util/SessionStorageConfiguration.cs
> +        public SessionStorageConfiguration(string storagePath, int sessionExpiredTime)
Can't we just name this class as SessionConfiguration rather than SessionStorageConfiguration?, Because `Timeout` doesn't have any relation with StorageConfiguration, but file StoragePath. Please change it a bit

2017-05-17 07:08 UTC, ummarbhutta commented on IotWeb Portable/Util/SessionStorageConfiguration.cs
>          public int SessionExpiredTime { get; set; }
Rename it to `Timeout`

2017-05-17 07:08 UTC, ummarbhutta commented on IotWeb Portable/Util/SessionHandler.cs
> +        {
Please change access specifier of this method, I don't this it is required to be exposed

2017-05-17 07:08 UTC, ummarbhutta commented on IotWeb Portable/Util/SessionHandler.cs
> +        {
Please change access specifier of this method, I don't this it is required to be exposed

2017-05-17 07:08 UTC, ummarbhutta commented on IotWeb Portable/Util/SessionHandler.cs
> +        {
- Please change access specifier of this method, I don't this it is required to be exposed
- Secondly if method is async use Async as postfix

2017-05-17 07:08 UTC, ummarbhutta commented on IotWeb Portable/Util/SessionHandler.cs
> +        {
Rename it to DestroySession

2017-05-24 07:12 UTC, mshoaibijaz commented on IotWeb NET45/IotWeb NET45.csproj
> +    </Reference>
Removed.

2017-08-04 06:21 UTC, ummarbhutta approved these changes

2017-08-04 06:27 UTC, merged